accent = "#5ec4b8"
cursor = "#d4956a"
foreground = "#a9b1d6"
background = "#1c1f26"
selection_foreground = "#1c1f26"
selection_background = "#5ec4b8"

color0 = "#32344a"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#5ec4b8"
color5 = "#ad8ee6"
color6 = "#4fb3b8"
color7 = "#787c99"
color8 = "#444b6a"
color9 = "#ff7a93"
color10 = "#b9f27c"
color11 = "#ff9e64"
color12 = "#33b5a8"
color13 = "#bb9af7"
color14 = "#5ec4b8"
color15 = "#acb0d0"
